version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: image/server/api/Dockerfile
    environment:
      - PORT=12345
    ports:
      - "12345:12345"
  web:
    build:
      context: .
      dockerfile: image/server/web/Dockerfile
    environment:
      - PORT=12346
      - SPIRIT_API_SERVER_ADDRESS=api:12345
    ports:
      - "12346:12346"
