# permissions for end users to view battles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: battle-viewer-role
rules:
- apiGroups:
  - spirits.dev
  resources:
  - battles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spirits.dev
  resources:
  - battles/status
  verbs:
  - get
