//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	api "github.com/ankeesler/spirits/pkg/api"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Battle)(nil), (*api.Battle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Battle_To_api_Battle(a.(*Battle), b.(*api.Battle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.Battle)(nil), (*Battle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_Battle_To_v1alpha1_Battle(a.(*api.Battle), b.(*Battle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BattleList)(nil), (*api.BattleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BattleList_To_api_BattleList(a.(*BattleList), b.(*api.BattleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.BattleList)(nil), (*BattleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_BattleList_To_v1alpha1_BattleList(a.(*api.BattleList), b.(*BattleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BattleSpec)(nil), (*api.BattleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BattleSpec_To_api_BattleSpec(a.(*BattleSpec), b.(*api.BattleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.BattleSpec)(nil), (*BattleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_BattleSpec_To_v1alpha1_BattleSpec(a.(*api.BattleSpec), b.(*BattleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BattleStatus)(nil), (*api.BattleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BattleStatus_To_api_BattleStatus(a.(*BattleStatus), b.(*api.BattleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.BattleStatus)(nil), (*BattleStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_BattleStatus_To_v1alpha1_BattleStatus(a.(*api.BattleStatus), b.(*BattleStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Spirit)(nil), (*api.Spirit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Spirit_To_api_Spirit(a.(*Spirit), b.(*api.Spirit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.Spirit)(nil), (*Spirit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_Spirit_To_v1alpha1_Spirit(a.(*api.Spirit), b.(*Spirit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SpiritList)(nil), (*api.SpiritList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpiritList_To_api_SpiritList(a.(*SpiritList), b.(*api.SpiritList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.SpiritList)(nil), (*SpiritList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_SpiritList_To_v1alpha1_SpiritList(a.(*api.SpiritList), b.(*SpiritList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SpiritSpec)(nil), (*api.SpiritSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpiritSpec_To_api_SpiritSpec(a.(*SpiritSpec), b.(*api.SpiritSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.SpiritSpec)(nil), (*SpiritSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_SpiritSpec_To_v1alpha1_SpiritSpec(a.(*api.SpiritSpec), b.(*SpiritSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SpiritStats)(nil), (*api.SpiritStats)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpiritStats_To_api_SpiritStats(a.(*SpiritStats), b.(*api.SpiritStats), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.SpiritStats)(nil), (*SpiritStats)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_SpiritStats_To_v1alpha1_SpiritStats(a.(*api.SpiritStats), b.(*SpiritStats), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SpiritStatus)(nil), (*api.SpiritStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SpiritStatus_To_api_SpiritStatus(a.(*SpiritStatus), b.(*api.SpiritStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.SpiritStatus)(nil), (*SpiritStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_SpiritStatus_To_v1alpha1_SpiritStatus(a.(*api.SpiritStatus), b.(*SpiritStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Battle_To_api_Battle(in *Battle, out *api.Battle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BattleSpec_To_api_BattleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BattleStatus_To_api_BattleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Battle_To_api_Battle is an autogenerated conversion function.
func Convert_v1alpha1_Battle_To_api_Battle(in *Battle, out *api.Battle, s conversion.Scope) error {
	return autoConvert_v1alpha1_Battle_To_api_Battle(in, out, s)
}

func autoConvert_api_Battle_To_v1alpha1_Battle(in *api.Battle, out *Battle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_api_BattleSpec_To_v1alpha1_BattleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_api_BattleStatus_To_v1alpha1_BattleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_api_Battle_To_v1alpha1_Battle is an autogenerated conversion function.
func Convert_api_Battle_To_v1alpha1_Battle(in *api.Battle, out *Battle, s conversion.Scope) error {
	return autoConvert_api_Battle_To_v1alpha1_Battle(in, out, s)
}

func autoConvert_v1alpha1_BattleList_To_api_BattleList(in *BattleList, out *api.BattleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]api.Battle)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BattleList_To_api_BattleList is an autogenerated conversion function.
func Convert_v1alpha1_BattleList_To_api_BattleList(in *BattleList, out *api.BattleList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BattleList_To_api_BattleList(in, out, s)
}

func autoConvert_api_BattleList_To_v1alpha1_BattleList(in *api.BattleList, out *BattleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Battle)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_api_BattleList_To_v1alpha1_BattleList is an autogenerated conversion function.
func Convert_api_BattleList_To_v1alpha1_BattleList(in *api.BattleList, out *BattleList, s conversion.Scope) error {
	return autoConvert_api_BattleList_To_v1alpha1_BattleList(in, out, s)
}

func autoConvert_v1alpha1_BattleSpec_To_api_BattleSpec(in *BattleSpec, out *api.BattleSpec, s conversion.Scope) error {
	out.Spirits = *(*[]string)(unsafe.Pointer(&in.Spirits))
	return nil
}

// Convert_v1alpha1_BattleSpec_To_api_BattleSpec is an autogenerated conversion function.
func Convert_v1alpha1_BattleSpec_To_api_BattleSpec(in *BattleSpec, out *api.BattleSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BattleSpec_To_api_BattleSpec(in, out, s)
}

func autoConvert_api_BattleSpec_To_v1alpha1_BattleSpec(in *api.BattleSpec, out *BattleSpec, s conversion.Scope) error {
	out.Spirits = *(*[]string)(unsafe.Pointer(&in.Spirits))
	return nil
}

// Convert_api_BattleSpec_To_v1alpha1_BattleSpec is an autogenerated conversion function.
func Convert_api_BattleSpec_To_v1alpha1_BattleSpec(in *api.BattleSpec, out *BattleSpec, s conversion.Scope) error {
	return autoConvert_api_BattleSpec_To_v1alpha1_BattleSpec(in, out, s)
}

func autoConvert_v1alpha1_BattleStatus_To_api_BattleStatus(in *BattleStatus, out *api.BattleStatus, s conversion.Scope) error {
	out.Phase = api.Phase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.InBattleSpirits = *(*[]string)(unsafe.Pointer(&in.InBattleSpirits))
	return nil
}

// Convert_v1alpha1_BattleStatus_To_api_BattleStatus is an autogenerated conversion function.
func Convert_v1alpha1_BattleStatus_To_api_BattleStatus(in *BattleStatus, out *api.BattleStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BattleStatus_To_api_BattleStatus(in, out, s)
}

func autoConvert_api_BattleStatus_To_v1alpha1_BattleStatus(in *api.BattleStatus, out *BattleStatus, s conversion.Scope) error {
	out.Phase = Phase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.InBattleSpirits = *(*[]string)(unsafe.Pointer(&in.InBattleSpirits))
	return nil
}

// Convert_api_BattleStatus_To_v1alpha1_BattleStatus is an autogenerated conversion function.
func Convert_api_BattleStatus_To_v1alpha1_BattleStatus(in *api.BattleStatus, out *BattleStatus, s conversion.Scope) error {
	return autoConvert_api_BattleStatus_To_v1alpha1_BattleStatus(in, out, s)
}

func autoConvert_v1alpha1_Spirit_To_api_Spirit(in *Spirit, out *api.Spirit, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SpiritSpec_To_api_SpiritSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SpiritStatus_To_api_SpiritStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Spirit_To_api_Spirit is an autogenerated conversion function.
func Convert_v1alpha1_Spirit_To_api_Spirit(in *Spirit, out *api.Spirit, s conversion.Scope) error {
	return autoConvert_v1alpha1_Spirit_To_api_Spirit(in, out, s)
}

func autoConvert_api_Spirit_To_v1alpha1_Spirit(in *api.Spirit, out *Spirit, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_api_SpiritSpec_To_v1alpha1_SpiritSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_api_SpiritStatus_To_v1alpha1_SpiritStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_api_Spirit_To_v1alpha1_Spirit is an autogenerated conversion function.
func Convert_api_Spirit_To_v1alpha1_Spirit(in *api.Spirit, out *Spirit, s conversion.Scope) error {
	return autoConvert_api_Spirit_To_v1alpha1_Spirit(in, out, s)
}

func autoConvert_v1alpha1_SpiritList_To_api_SpiritList(in *SpiritList, out *api.SpiritList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]api.Spirit)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SpiritList_To_api_SpiritList is an autogenerated conversion function.
func Convert_v1alpha1_SpiritList_To_api_SpiritList(in *SpiritList, out *api.SpiritList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SpiritList_To_api_SpiritList(in, out, s)
}

func autoConvert_api_SpiritList_To_v1alpha1_SpiritList(in *api.SpiritList, out *SpiritList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Spirit)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_api_SpiritList_To_v1alpha1_SpiritList is an autogenerated conversion function.
func Convert_api_SpiritList_To_v1alpha1_SpiritList(in *api.SpiritList, out *SpiritList, s conversion.Scope) error {
	return autoConvert_api_SpiritList_To_v1alpha1_SpiritList(in, out, s)
}

func autoConvert_v1alpha1_SpiritSpec_To_api_SpiritSpec(in *SpiritSpec, out *api.SpiritSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_SpiritStats_To_api_SpiritStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	out.Actions = *(*[]string)(unsafe.Pointer(&in.Actions))
	out.Intelligence = api.SpiritIntelligence(in.Intelligence)
	return nil
}

// Convert_v1alpha1_SpiritSpec_To_api_SpiritSpec is an autogenerated conversion function.
func Convert_v1alpha1_SpiritSpec_To_api_SpiritSpec(in *SpiritSpec, out *api.SpiritSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SpiritSpec_To_api_SpiritSpec(in, out, s)
}

func autoConvert_api_SpiritSpec_To_v1alpha1_SpiritSpec(in *api.SpiritSpec, out *SpiritSpec, s conversion.Scope) error {
	if err := Convert_api_SpiritStats_To_v1alpha1_SpiritStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	out.Actions = *(*[]string)(unsafe.Pointer(&in.Actions))
	out.Intelligence = SpiritIntelligence(in.Intelligence)
	return nil
}

// Convert_api_SpiritSpec_To_v1alpha1_SpiritSpec is an autogenerated conversion function.
func Convert_api_SpiritSpec_To_v1alpha1_SpiritSpec(in *api.SpiritSpec, out *SpiritSpec, s conversion.Scope) error {
	return autoConvert_api_SpiritSpec_To_v1alpha1_SpiritSpec(in, out, s)
}

func autoConvert_v1alpha1_SpiritStats_To_api_SpiritStats(in *SpiritStats, out *api.SpiritStats, s conversion.Scope) error {
	out.Health = in.Health
	out.Power = in.Power
	out.Armor = in.Armor
	out.Agility = in.Agility
	return nil
}

// Convert_v1alpha1_SpiritStats_To_api_SpiritStats is an autogenerated conversion function.
func Convert_v1alpha1_SpiritStats_To_api_SpiritStats(in *SpiritStats, out *api.SpiritStats, s conversion.Scope) error {
	return autoConvert_v1alpha1_SpiritStats_To_api_SpiritStats(in, out, s)
}

func autoConvert_api_SpiritStats_To_v1alpha1_SpiritStats(in *api.SpiritStats, out *SpiritStats, s conversion.Scope) error {
	out.Health = in.Health
	out.Power = in.Power
	out.Armor = in.Armor
	out.Agility = in.Agility
	return nil
}

// Convert_api_SpiritStats_To_v1alpha1_SpiritStats is an autogenerated conversion function.
func Convert_api_SpiritStats_To_v1alpha1_SpiritStats(in *api.SpiritStats, out *SpiritStats, s conversion.Scope) error {
	return autoConvert_api_SpiritStats_To_v1alpha1_SpiritStats(in, out, s)
}

func autoConvert_v1alpha1_SpiritStatus_To_api_SpiritStatus(in *SpiritStatus, out *api.SpiritStatus, s conversion.Scope) error {
	out.Phase = api.Phase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_SpiritStatus_To_api_SpiritStatus is an autogenerated conversion function.
func Convert_v1alpha1_SpiritStatus_To_api_SpiritStatus(in *SpiritStatus, out *api.SpiritStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SpiritStatus_To_api_SpiritStatus(in, out, s)
}

func autoConvert_api_SpiritStatus_To_v1alpha1_SpiritStatus(in *api.SpiritStatus, out *SpiritStatus, s conversion.Scope) error {
	out.Phase = Phase(in.Phase)
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_api_SpiritStatus_To_v1alpha1_SpiritStatus is an autogenerated conversion function.
func Convert_api_SpiritStatus_To_v1alpha1_SpiritStatus(in *api.SpiritStatus, out *SpiritStatus, s conversion.Scope) error {
	return autoConvert_api_SpiritStatus_To_v1alpha1_SpiritStatus(in, out, s)
}
