// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/ankeesler/spirits/pkg/apis/spirits/input/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeActionCalls implements ActionCallInterface
type FakeActionCalls struct {
	Fake *FakeInputV1alpha1
	ns   string
}

var actioncallsResource = schema.GroupVersionResource{Group: "input.spirits.ankeesler.github.io", Version: "v1alpha1", Resource: "actioncalls"}

var actioncallsKind = schema.GroupVersionKind{Group: "input.spirits.ankeesler.github.io", Version: "v1alpha1", Kind: "ActionCall"}

// Create takes the representation of a actionCall and creates it.  Returns the server's representation of the actionCall, and an error, if there is any.
func (c *FakeActionCalls) Create(ctx context.Context, actionCall *v1alpha1.ActionCall, opts v1.CreateOptions) (result *v1alpha1.ActionCall, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(actioncallsResource, c.ns, actionCall), &v1alpha1.ActionCall{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionCall), err
}
