---
apiVersion: v1
kind: Namespace
metadata:
  namespace: spirits
  name: spirits
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: spirits
  name: spirits-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: spirits
  name: spirits-controller-manager:spirits-controller-manager
subjects:
- kind: ServiceAccount
  name: spirits-controller-manager
  namespace: spirits
roleRef:
  kind: ClusterRole
  name: spirits-controller-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spirits-controller-manager
  name: spirits-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spirits-controller-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spirits-controller-manager
    spec:
      containers:
      - image: spirits-controller-manager:latest
        name: spirits-controller-manager
        serviceAccount: spirits-controller-manager