BEGIN {
    printf("// THIS FILE IS GENERATED BY %s\n", source);
    printf("\n");

    if (output_type == "c") {
        printf("#include \"locations.h\"\n");
        printf("\n");
        printf("#include <stdlib.h>\n");
        printf("\n");
        printf("#include \"location.h\"\n");
        printf("\n");
        printf("#include \"locations_menu_items.c\"\n");
        printf("\n");
        printf("const location_t locations[] = {\n");
    } else {
        printf("#ifndef __LOCATIONS_H__\n");
        printf("#define __LOCATIONS_H__\n");
        printf("\n");
        printf("#include \"location.h\"\n");
        printf("\n");
        printf("extern const location_t locations[];\n");
        printf("\n");
    }
}

// {
    if (output_type == "c") {
        location = $1;
        gsub(" ", "_", location);

        printf("  {\n");
        printf("    .id = %d,\n", id);
        printf("    .name = \"%s\",\n", $1);
        printf("    .menu = {\n");
        printf("      .title = \"%s\",\n", $1);
        printf("      .items = {\n");

        for (i = 3; i < NF; i++) {
            name = $i;
            i++;
            description = $i;
            
            printf("        {\n");
            printf("          .name = \"%s\",\n", name);
            printf("          .description = \"%s\",\n", description);
            printf("          .run = %s_menu_item_%s,\n", location, name);
            printf("        },\n");
        }

        if (id > 0) {
            next_location = locations[id-1];
            printf("        {\n");
            printf("          .name = \"Go to %s\",\n", next_location);
            printf("          .description = NULL,\n", description);
            printf("          .run = %s_menu_item_go_back,\n", location);
            printf("        },\n");
        }

        printf("        { .name = NULL },\n", $1);
        printf("      }\n");
        printf("    }\n");
        printf("  },\n");
        printf("\n");

        locations_array_contents = sprintf("%s\n  &%s,", locations_array_contents, location);
        locations[id] = $1;
        id++;
    } else {
    }
}

END {
    if (output_type == "c") {
        printf("};\n");
    } else {
        printf("\n");
        printf("#endif /* __LOCATIONS_H__ */\n");
    }
}
