// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: spirits/v1/battle.proto

package spiritsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BattleState describes which stage a Battle is in.
//
// The Battle stages go like this:
//   Pending (waiting for Spirit's to join)
//     |
//     v
//   Started (started executing)
//     ^
//     |
//     v
//   Waiting (waiting for input from user)
//     |
//     v
//   Finished (execution finished)
//    ...
// <any state>
//     |
//     v
//   Cancelled (battle has been cancelled)
//    ...
// <any state>
//     |
//     v
//   Error (battle has entered into a failure mode)
type BattleState int32

const (
	BattleState_BATTLE_STATE_UNSPECIFIED BattleState = 0
	BattleState_BATTLE_STATE_PENDING     BattleState = 1
	BattleState_BATTLE_STATE_STARTED     BattleState = 2
	BattleState_BATTLE_STATE_WAITING     BattleState = 4
	BattleState_BATTLE_STATE_FINISHED    BattleState = 5
	BattleState_BATTLE_STATE_CANCELLED   BattleState = 6
	BattleState_BATTLE_STATE_ERROR       BattleState = 7
)

// Enum value maps for BattleState.
var (
	BattleState_name = map[int32]string{
		0: "BATTLE_STATE_UNSPECIFIED",
		1: "BATTLE_STATE_PENDING",
		2: "BATTLE_STATE_STARTED",
		4: "BATTLE_STATE_WAITING",
		5: "BATTLE_STATE_FINISHED",
		6: "BATTLE_STATE_CANCELLED",
		7: "BATTLE_STATE_ERROR",
	}
	BattleState_value = map[string]int32{
		"BATTLE_STATE_UNSPECIFIED": 0,
		"BATTLE_STATE_PENDING":     1,
		"BATTLE_STATE_STARTED":     2,
		"BATTLE_STATE_WAITING":     4,
		"BATTLE_STATE_FINISHED":    5,
		"BATTLE_STATE_CANCELLED":   6,
		"BATTLE_STATE_ERROR":       7,
	}
)

func (x BattleState) Enum() *BattleState {
	p := new(BattleState)
	*p = x
	return p
}

func (x BattleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleState) Descriptor() protoreflect.EnumDescriptor {
	return file_spirits_v1_battle_proto_enumTypes[0].Descriptor()
}

func (BattleState) Type() protoreflect.EnumType {
	return &file_spirits_v1_battle_proto_enumTypes[0]
}

func (x BattleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleState.Descriptor instead.
func (BattleState) EnumDescriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{0}
}

// BattleTeamSpiritIntelligence describes how a Spirit will decide to take
// SpiritAction in a Battle.
type BattleTeamSpiritIntelligence int32

const (
	BattleTeamSpiritIntelligence_BATTLE_TEAM_SPIRIT_INTELLIGENCE_UNSPECIFIED BattleTeamSpiritIntelligence = 0
	// A human will decide this Spirit's SpiritAction's via CallAction.
	BattleTeamSpiritIntelligence_BATTLE_TEAM_SPIRIT_INTELLIGENCE_HUMAN BattleTeamSpiritIntelligence = 1
	// This Spirit will chose SpiritActions randomly.
	BattleTeamSpiritIntelligence_BATTLE_TEAM_SPIRIT_INTELLIGENCE_RANDOM BattleTeamSpiritIntelligence = 2
)

// Enum value maps for BattleTeamSpiritIntelligence.
var (
	BattleTeamSpiritIntelligence_name = map[int32]string{
		0: "BATTLE_TEAM_SPIRIT_INTELLIGENCE_UNSPECIFIED",
		1: "BATTLE_TEAM_SPIRIT_INTELLIGENCE_HUMAN",
		2: "BATTLE_TEAM_SPIRIT_INTELLIGENCE_RANDOM",
	}
	BattleTeamSpiritIntelligence_value = map[string]int32{
		"BATTLE_TEAM_SPIRIT_INTELLIGENCE_UNSPECIFIED": 0,
		"BATTLE_TEAM_SPIRIT_INTELLIGENCE_HUMAN":       1,
		"BATTLE_TEAM_SPIRIT_INTELLIGENCE_RANDOM":      2,
	}
)

func (x BattleTeamSpiritIntelligence) Enum() *BattleTeamSpiritIntelligence {
	p := new(BattleTeamSpiritIntelligence)
	*p = x
	return p
}

func (x BattleTeamSpiritIntelligence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleTeamSpiritIntelligence) Descriptor() protoreflect.EnumDescriptor {
	return file_spirits_v1_battle_proto_enumTypes[1].Descriptor()
}

func (BattleTeamSpiritIntelligence) Type() protoreflect.EnumType {
	return &file_spirits_v1_battle_proto_enumTypes[1]
}

func (x BattleTeamSpiritIntelligence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleTeamSpiritIntelligence.Descriptor instead.
func (BattleTeamSpiritIntelligence) EnumDescriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{1}
}

type CreateBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBattleRequest) Reset() {
	*x = CreateBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleRequest) ProtoMessage() {}

func (x *CreateBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleRequest.ProtoReflect.Descriptor instead.
func (*CreateBattleRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{0}
}

type CreateBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The created Battle.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *CreateBattleResponse) Reset() {
	*x = CreateBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleResponse) ProtoMessage() {}

func (x *CreateBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleResponse.ProtoReflect.Descriptor instead.
func (*CreateBattleResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBattleResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type ListBattlesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBattlesRequest) Reset() {
	*x = ListBattlesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBattlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBattlesRequest) ProtoMessage() {}

func (x *ListBattlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBattlesRequest.ProtoReflect.Descriptor instead.
func (*ListBattlesRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{2}
}

type ListBattlesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The known Battle's.
	Battles []*Battle `protobuf:"bytes,1,rep,name=battles,proto3" json:"battles,omitempty"`
}

func (x *ListBattlesResponse) Reset() {
	*x = ListBattlesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBattlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBattlesResponse) ProtoMessage() {}

func (x *ListBattlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBattlesResponse.ProtoReflect.Descriptor instead.
func (*ListBattlesResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{3}
}

func (x *ListBattlesResponse) GetBattles() []*Battle {
	if x != nil {
		return x.Battles
	}
	return nil
}

type WatchBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to watch.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WatchBattleRequest) Reset() {
	*x = WatchBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBattleRequest) ProtoMessage() {}

func (x *WatchBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBattleRequest.ProtoReflect.Descriptor instead.
func (*WatchBattleRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{4}
}

func (x *WatchBattleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WatchBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Battle that has been updated.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *WatchBattleResponse) Reset() {
	*x = WatchBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBattleResponse) ProtoMessage() {}

func (x *WatchBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBattleResponse.ProtoReflect.Descriptor instead.
func (*WatchBattleResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{5}
}

func (x *WatchBattleResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type AddBattleTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to which to add this BattleTeam.
	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	// The name of the new BattleTeam.
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
}

func (x *AddBattleTeamRequest) Reset() {
	*x = AddBattleTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBattleTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBattleTeamRequest) ProtoMessage() {}

func (x *AddBattleTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBattleTeamRequest.ProtoReflect.Descriptor instead.
func (*AddBattleTeamRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{6}
}

func (x *AddBattleTeamRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *AddBattleTeamRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type AddBattleTeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The newly updated Battle.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *AddBattleTeamResponse) Reset() {
	*x = AddBattleTeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBattleTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBattleTeamResponse) ProtoMessage() {}

func (x *AddBattleTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBattleTeamResponse.ProtoReflect.Descriptor instead.
func (*AddBattleTeamResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{7}
}

func (x *AddBattleTeamResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type AddBattleTeamSpiritRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to which to add this BattleTeamSpirit.
	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	// The name of the BattleTeam to which to add the Spirit.
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	// The id of the Spirit to add to the BattleTeam.
	SpiritId string `protobuf:"bytes,3,opt,name=spirit_id,json=spiritId,proto3" json:"spirit_id,omitempty"`
	// The intelligence that this Spirit will use.
	Intelligence BattleTeamSpiritIntelligence `protobuf:"varint,4,opt,name=intelligence,proto3,enum=spirits.v1.BattleTeamSpiritIntelligence" json:"intelligence,omitempty"`
	// The seed to use for any random actions.
	Seed int64 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *AddBattleTeamSpiritRequest) Reset() {
	*x = AddBattleTeamSpiritRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBattleTeamSpiritRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBattleTeamSpiritRequest) ProtoMessage() {}

func (x *AddBattleTeamSpiritRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBattleTeamSpiritRequest.ProtoReflect.Descriptor instead.
func (*AddBattleTeamSpiritRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{8}
}

func (x *AddBattleTeamSpiritRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *AddBattleTeamSpiritRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *AddBattleTeamSpiritRequest) GetSpiritId() string {
	if x != nil {
		return x.SpiritId
	}
	return ""
}

func (x *AddBattleTeamSpiritRequest) GetIntelligence() BattleTeamSpiritIntelligence {
	if x != nil {
		return x.Intelligence
	}
	return BattleTeamSpiritIntelligence_BATTLE_TEAM_SPIRIT_INTELLIGENCE_UNSPECIFIED
}

func (x *AddBattleTeamSpiritRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type AddBattleTeamSpiritResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The newly updated Battle.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *AddBattleTeamSpiritResponse) Reset() {
	*x = AddBattleTeamSpiritResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBattleTeamSpiritResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBattleTeamSpiritResponse) ProtoMessage() {}

func (x *AddBattleTeamSpiritResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBattleTeamSpiritResponse.ProtoReflect.Descriptor instead.
func (*AddBattleTeamSpiritResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{9}
}

func (x *AddBattleTeamSpiritResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type StartBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to start.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartBattleRequest) Reset() {
	*x = StartBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleRequest) ProtoMessage() {}

func (x *StartBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleRequest.ProtoReflect.Descriptor instead.
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{10}
}

func (x *StartBattleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The newly started Battle.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *StartBattleResponse) Reset() {
	*x = StartBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleResponse) ProtoMessage() {}

func (x *StartBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleResponse.ProtoReflect.Descriptor instead.
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{11}
}

func (x *StartBattleResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type CancelBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to cancel.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CancelBattleRequest) Reset() {
	*x = CancelBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBattleRequest) ProtoMessage() {}

func (x *CancelBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBattleRequest.ProtoReflect.Descriptor instead.
func (*CancelBattleRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{12}
}

func (x *CancelBattleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The newly cancelled Battle.
	Battle *Battle `protobuf:"bytes,1,opt,name=battle,proto3" json:"battle,omitempty"`
}

func (x *CancelBattleResponse) Reset() {
	*x = CancelBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBattleResponse) ProtoMessage() {}

func (x *CancelBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBattleResponse.ProtoReflect.Descriptor instead.
func (*CancelBattleResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{13}
}

func (x *CancelBattleResponse) GetBattle() *Battle {
	if x != nil {
		return x.Battle
	}
	return nil
}

type CallActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Battle to which this call applies.
	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	// The id of the Spirit to which this call applies.
	SpiritId string `protobuf:"bytes,2,opt,name=spirit_id,json=spiritId,proto3" json:"spirit_id,omitempty"`
	// The turn on which this Action call applies.
	Turn int64 `protobuf:"varint,3,opt,name=turn,proto3" json:"turn,omitempty"`
	// The name of the Action to call.
	ActionName string `protobuf:"bytes,4,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	// The Spirit's to which this action should be applied.
	TargetSpiritIds []string `protobuf:"bytes,5,rep,name=target_spirit_ids,json=targetSpiritIds,proto3" json:"target_spirit_ids,omitempty"`
}

func (x *CallActionRequest) Reset() {
	*x = CallActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallActionRequest) ProtoMessage() {}

func (x *CallActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallActionRequest.ProtoReflect.Descriptor instead.
func (*CallActionRequest) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{14}
}

func (x *CallActionRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CallActionRequest) GetSpiritId() string {
	if x != nil {
		return x.SpiritId
	}
	return ""
}

func (x *CallActionRequest) GetTurn() int64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *CallActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *CallActionRequest) GetTargetSpiritIds() []string {
	if x != nil {
		return x.TargetSpiritIds
	}
	return nil
}

type CallActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CallActionResponse) Reset() {
	*x = CallActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallActionResponse) ProtoMessage() {}

func (x *CallActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallActionResponse.ProtoReflect.Descriptor instead.
func (*CallActionResponse) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{15}
}

// Battle describes a single battle royale amongst Spirit's.
type Battle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metadata about this Battle.
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Current state of the Battle.
	//
	// If this is BATTLE_STATE_ERROR, the error_message field will be set.
	State BattleState `protobuf:"varint,2,opt,name=state,proto3,enum=spirits.v1.BattleState" json:"state,omitempty"`
	// Description of error state.
	//
	// This is only set when the Battle is in BattleState BATTLE_STATE_ERROR.
	ErrorMessage *string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// List of BattleTeam's participating in this Battle.
	//
	// This list references the original Spirit's before any modifications over
	// the course of a Battle.
	Teams []*BattleTeam `protobuf:"bytes,4,rep,name=teams,proto3" json:"teams,omitempty"`
	// List of BattleTeams's participating in this Battle as they exist in the
	// Battle.
	//
	// This list references the current state of Spirit's in this Battle.
	InBattleTeams []*BattleTeam `protobuf:"bytes,5,rep,name=in_battle_teams,json=inBattleTeams,proto3" json:"in_battle_teams,omitempty"`
	// The next Spirit's to run.
	//
	// This is only valid when the BattleState is BATTLE_STATE_RUNNING or
	// BATTLE_STATE_WAITING.
	//
	// Note that this list is not complete - it may contain 0 or more entries.
	NextSpiritIds []string `protobuf:"bytes,6,rep,name=next_spirit_ids,json=nextSpiritIds,proto3" json:"next_spirit_ids,omitempty"`
	// The number of turns that this battle has run.
	Turns int64 `protobuf:"varint,7,opt,name=turns,proto3" json:"turns,omitempty"`
}

func (x *Battle) Reset() {
	*x = Battle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Battle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Battle) ProtoMessage() {}

func (x *Battle) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Battle.ProtoReflect.Descriptor instead.
func (*Battle) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{16}
}

func (x *Battle) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Battle) GetState() BattleState {
	if x != nil {
		return x.State
	}
	return BattleState_BATTLE_STATE_UNSPECIFIED
}

func (x *Battle) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Battle) GetTeams() []*BattleTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *Battle) GetInBattleTeams() []*BattleTeam {
	if x != nil {
		return x.InBattleTeams
	}
	return nil
}

func (x *Battle) GetNextSpiritIds() []string {
	if x != nil {
		return x.NextSpiritIds
	}
	return nil
}

func (x *Battle) GetTurns() int64 {
	if x != nil {
		return x.Turns
	}
	return 0
}

// BattleTeam is a group of Spirit's working together in a Battle.
type BattleTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique (within Battle) identifier of BattleTeam.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The list of BattleTeamSpirit's in this BattleTeam.
	Spirits []*BattleTeamSpirit `protobuf:"bytes,2,rep,name=spirits,proto3" json:"spirits,omitempty"`
}

func (x *BattleTeam) Reset() {
	*x = BattleTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleTeam) ProtoMessage() {}

func (x *BattleTeam) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleTeam.ProtoReflect.Descriptor instead.
func (*BattleTeam) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{17}
}

func (x *BattleTeam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BattleTeam) GetSpirits() []*BattleTeamSpirit {
	if x != nil {
		return x.Spirits
	}
	return nil
}

// BattleTeamSpirit is a reference to a Spirit as it exists in a BattleTeam.
type BattleTeamSpirit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Spirit as it exists in this BattleTeam.
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit,proto3" json:"spirit,omitempty"`
	// The intelligence that this Spirit will use.
	Intelligence BattleTeamSpiritIntelligence `protobuf:"varint,2,opt,name=intelligence,proto3,enum=spirits.v1.BattleTeamSpiritIntelligence" json:"intelligence,omitempty"`
	// The seed to use for any random actions.
	Seed int64 `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *BattleTeamSpirit) Reset() {
	*x = BattleTeamSpirit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spirits_v1_battle_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleTeamSpirit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleTeamSpirit) ProtoMessage() {}

func (x *BattleTeamSpirit) ProtoReflect() protoreflect.Message {
	mi := &file_spirits_v1_battle_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleTeamSpirit.ProtoReflect.Descriptor instead.
func (*BattleTeamSpirit) Descriptor() ([]byte, []int) {
	return file_spirits_v1_battle_proto_rawDescGZIP(), []int{18}
}

func (x *BattleTeamSpirit) GetSpirit() *Spirit {
	if x != nil {
		return x.Spirit
	}
	return nil
}

func (x *BattleTeamSpirit) GetIntelligence() BattleTeamSpiritIntelligence {
	if x != nil {
		return x.Intelligence
	}
	return BattleTeamSpiritIntelligence_BATTLE_TEAM_SPIRIT_INTELLIGENCE_UNSPECIFIED
}

func (x *BattleTeamSpirit) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

var File_spirits_v1_battle_proto protoreflect.FileDescriptor

var file_spirits_v1_battle_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x73, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x07, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x07, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x41, 0x0a, 0x13, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65,
	0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x1a,
	0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69,
	0x72, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x49,
	0x64, 0x12, 0x4c, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53,
	0x70, 0x69, 0x72, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x24,
	0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42,
	0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x49, 0x64, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc5, 0x02, 0x0a, 0x06, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x69, 0x72,
	0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d,
	0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x69, 0x6e, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x74,
	0x65, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x70, 0x69,
	0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x0d, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74,
	0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x75, 0x72,
	0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x58, 0x0a, 0x0a, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72,
	0x69, 0x74, 0x52, 0x07, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x10,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x12, 0x2a, 0x0a, 0x06, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x52, 0x06, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x12, 0x4c, 0x0a, 0x0c,
	0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x28, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0c, 0x69, 0x6e,
	0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x2a, 0xc8,
	0x01, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x18, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e,
	0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x18, 0x0a, 0x14, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x41,
	0x54, 0x54, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53,
	0x48, 0x45, 0x44, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10,
	0x06, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x07, 0x2a, 0xa6, 0x01, 0x0a, 0x1c, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x2b, 0x42, 0x41,
	0x54, 0x54, 0x4c, 0x45, 0x5f, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x53, 0x50, 0x49, 0x52, 0x49, 0x54,
	0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4c, 0x4c, 0x49, 0x47, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x29, 0x0a, 0x25, 0x42,
	0x41, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x53, 0x50, 0x49, 0x52, 0x49,
	0x54, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x4c, 0x4c, 0x49, 0x47, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x48,
	0x55, 0x4d, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x2a, 0x0a, 0x26, 0x42, 0x41, 0x54, 0x54, 0x4c, 0x45,
	0x5f, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x53, 0x50, 0x49, 0x52, 0x49, 0x54, 0x5f, 0x49, 0x4e, 0x54,
	0x45, 0x4c, 0x4c, 0x49, 0x47, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d,
	0x10, 0x02, 0x32, 0xc2, 0x05, 0x0a, 0x0d, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x50, 0x0a,
	0x0b, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x73,
	0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x56, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x12, 0x20, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x12, 0x26,
	0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x12, 0x1e, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x6c,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xa1, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x6b, 0x65, 0x65, 0x73, 0x6c, 0x65, 0x72, 0x2f,
	0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x53, 0x70, 0x69,
	0x72, 0x69, 0x74, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74,
	0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b,
	0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_spirits_v1_battle_proto_rawDescOnce sync.Once
	file_spirits_v1_battle_proto_rawDescData = file_spirits_v1_battle_proto_rawDesc
)

func file_spirits_v1_battle_proto_rawDescGZIP() []byte {
	file_spirits_v1_battle_proto_rawDescOnce.Do(func() {
		file_spirits_v1_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_spirits_v1_battle_proto_rawDescData)
	})
	return file_spirits_v1_battle_proto_rawDescData
}

var file_spirits_v1_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spirits_v1_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_spirits_v1_battle_proto_goTypes = []interface{}{
	(BattleState)(0),                    // 0: spirits.v1.BattleState
	(BattleTeamSpiritIntelligence)(0),   // 1: spirits.v1.BattleTeamSpiritIntelligence
	(*CreateBattleRequest)(nil),         // 2: spirits.v1.CreateBattleRequest
	(*CreateBattleResponse)(nil),        // 3: spirits.v1.CreateBattleResponse
	(*ListBattlesRequest)(nil),          // 4: spirits.v1.ListBattlesRequest
	(*ListBattlesResponse)(nil),         // 5: spirits.v1.ListBattlesResponse
	(*WatchBattleRequest)(nil),          // 6: spirits.v1.WatchBattleRequest
	(*WatchBattleResponse)(nil),         // 7: spirits.v1.WatchBattleResponse
	(*AddBattleTeamRequest)(nil),        // 8: spirits.v1.AddBattleTeamRequest
	(*AddBattleTeamResponse)(nil),       // 9: spirits.v1.AddBattleTeamResponse
	(*AddBattleTeamSpiritRequest)(nil),  // 10: spirits.v1.AddBattleTeamSpiritRequest
	(*AddBattleTeamSpiritResponse)(nil), // 11: spirits.v1.AddBattleTeamSpiritResponse
	(*StartBattleRequest)(nil),          // 12: spirits.v1.StartBattleRequest
	(*StartBattleResponse)(nil),         // 13: spirits.v1.StartBattleResponse
	(*CancelBattleRequest)(nil),         // 14: spirits.v1.CancelBattleRequest
	(*CancelBattleResponse)(nil),        // 15: spirits.v1.CancelBattleResponse
	(*CallActionRequest)(nil),           // 16: spirits.v1.CallActionRequest
	(*CallActionResponse)(nil),          // 17: spirits.v1.CallActionResponse
	(*Battle)(nil),                      // 18: spirits.v1.Battle
	(*BattleTeam)(nil),                  // 19: spirits.v1.BattleTeam
	(*BattleTeamSpirit)(nil),            // 20: spirits.v1.BattleTeamSpirit
	(*Meta)(nil),                        // 21: spirits.v1.Meta
	(*Spirit)(nil),                      // 22: spirits.v1.Spirit
}
var file_spirits_v1_battle_proto_depIdxs = []int32{
	18, // 0: spirits.v1.CreateBattleResponse.battle:type_name -> spirits.v1.Battle
	18, // 1: spirits.v1.ListBattlesResponse.battles:type_name -> spirits.v1.Battle
	18, // 2: spirits.v1.WatchBattleResponse.battle:type_name -> spirits.v1.Battle
	18, // 3: spirits.v1.AddBattleTeamResponse.battle:type_name -> spirits.v1.Battle
	1,  // 4: spirits.v1.AddBattleTeamSpiritRequest.intelligence:type_name -> spirits.v1.BattleTeamSpiritIntelligence
	18, // 5: spirits.v1.AddBattleTeamSpiritResponse.battle:type_name -> spirits.v1.Battle
	18, // 6: spirits.v1.StartBattleResponse.battle:type_name -> spirits.v1.Battle
	18, // 7: spirits.v1.CancelBattleResponse.battle:type_name -> spirits.v1.Battle
	21, // 8: spirits.v1.Battle.meta:type_name -> spirits.v1.Meta
	0,  // 9: spirits.v1.Battle.state:type_name -> spirits.v1.BattleState
	19, // 10: spirits.v1.Battle.teams:type_name -> spirits.v1.BattleTeam
	19, // 11: spirits.v1.Battle.in_battle_teams:type_name -> spirits.v1.BattleTeam
	20, // 12: spirits.v1.BattleTeam.spirits:type_name -> spirits.v1.BattleTeamSpirit
	22, // 13: spirits.v1.BattleTeamSpirit.spirit:type_name -> spirits.v1.Spirit
	1,  // 14: spirits.v1.BattleTeamSpirit.intelligence:type_name -> spirits.v1.BattleTeamSpiritIntelligence
	2,  // 15: spirits.v1.BattleService.CreateBattle:input_type -> spirits.v1.CreateBattleRequest
	6,  // 16: spirits.v1.BattleService.WatchBattle:input_type -> spirits.v1.WatchBattleRequest
	4,  // 17: spirits.v1.BattleService.ListBattles:input_type -> spirits.v1.ListBattlesRequest
	8,  // 18: spirits.v1.BattleService.AddBattleTeam:input_type -> spirits.v1.AddBattleTeamRequest
	10, // 19: spirits.v1.BattleService.AddBattleTeamSpirit:input_type -> spirits.v1.AddBattleTeamSpiritRequest
	12, // 20: spirits.v1.BattleService.StartBattle:input_type -> spirits.v1.StartBattleRequest
	14, // 21: spirits.v1.BattleService.CancelBattle:input_type -> spirits.v1.CancelBattleRequest
	16, // 22: spirits.v1.BattleService.CallAction:input_type -> spirits.v1.CallActionRequest
	3,  // 23: spirits.v1.BattleService.CreateBattle:output_type -> spirits.v1.CreateBattleResponse
	7,  // 24: spirits.v1.BattleService.WatchBattle:output_type -> spirits.v1.WatchBattleResponse
	5,  // 25: spirits.v1.BattleService.ListBattles:output_type -> spirits.v1.ListBattlesResponse
	9,  // 26: spirits.v1.BattleService.AddBattleTeam:output_type -> spirits.v1.AddBattleTeamResponse
	11, // 27: spirits.v1.BattleService.AddBattleTeamSpirit:output_type -> spirits.v1.AddBattleTeamSpiritResponse
	13, // 28: spirits.v1.BattleService.StartBattle:output_type -> spirits.v1.StartBattleResponse
	15, // 29: spirits.v1.BattleService.CancelBattle:output_type -> spirits.v1.CancelBattleResponse
	17, // 30: spirits.v1.BattleService.CallAction:output_type -> spirits.v1.CallActionResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_spirits_v1_battle_proto_init() }
func file_spirits_v1_battle_proto_init() {
	if File_spirits_v1_battle_proto != nil {
		return
	}
	file_spirits_v1_meta_proto_init()
	file_spirits_v1_spirit_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_spirits_v1_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBattlesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBattlesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBattleTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBattleTeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBattleTeamSpiritRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBattleTeamSpiritResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Battle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spirits_v1_battle_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleTeamSpirit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spirits_v1_battle_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spirits_v1_battle_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spirits_v1_battle_proto_goTypes,
		DependencyIndexes: file_spirits_v1_battle_proto_depIdxs,
		EnumInfos:         file_spirits_v1_battle_proto_enumTypes,
		MessageInfos:      file_spirits_v1_battle_proto_msgTypes,
	}.Build()
	File_spirits_v1_battle_proto = out.File
	file_spirits_v1_battle_proto_rawDesc = nil
	file_spirits_v1_battle_proto_goTypes = nil
	file_spirits_v1_battle_proto_depIdxs = nil
}
