//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRun) DeepCopyInto(out *ActionRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRun.
func (in *ActionRun) DeepCopy() *ActionRun {
	if in == nil {
		return nil
	}
	out := new(ActionRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRunSpec) DeepCopyInto(out *ActionRunSpec) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.To.DeepCopyInto(&out.To)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRunSpec.
func (in *ActionRunSpec) DeepCopy() *ActionRunSpec {
	if in == nil {
		return nil
	}
	out := new(ActionRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRunStatus) DeepCopyInto(out *ActionRunStatus) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.To.DeepCopyInto(&out.To)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRunStatus.
func (in *ActionRunStatus) DeepCopy() *ActionRunStatus {
	if in == nil {
		return nil
	}
	out := new(ActionRunStatus)
	in.DeepCopyInto(out)
	return out
}
