name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v1
      
    - name: Mod
      run: go mod download

    - name: Fmt
      run: test -z "$(go fmt ./...)"
      
    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...
