name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Mod
      run: go mod download
    - name: Fmt
      run: test -z "$(go fmt ./...)"
    - name: Vet
      run: go vet -v ./...
    - name: Test
      run: go test -race -v ./...

  test-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm install
    - run: echo TODO

  build:
    needs: [test-web, test-api]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankeesler/spirits-manager:latest

  test-integration:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.2.0
    - name: Deploy
      run: kubectl apply -f config -f config/zz_generated_crds -f config/zz_generated_rbac
    - name: Check Deploy
      run: kubectl wait -n spirits deploy spirits-manager --for condition=Ready
    - name: Mod
      run: go mod download
    - name: Test
      run: go test -v ./test/...
      env:
        SPIRITS_TEST_INTEGRATION: 1

  deploy:
    needs: [test-integration]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#         heroku_app_name: oh-great-spirits
#         heroku_email: ankeesler1@gmail.com
#         healthcheck: "https://oh-great-spirits.herokuapp.com"
#         rollbackonhealthcheckfailed: true
#         usedocker: true
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
      working-directory: test
    - run: echo npm test
      working-directory: test
      env: 
        SPIRITS_TEST_URL: "https://oh-great-spirits.herokuapp.com"
