name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up chromedriver
      uses: nanasess/setup-chromedriver@v1
      
    - name: Mod
      run: go mod download

    - name: Fmt
      run: test -z "$(go fmt ./...)"
      
    - name: Vet
      run: go vet -v ./...

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: oh-great-spirits
        heroku_email: ankeesler1@gmail.com
        healthcheck: "https://oh-great-spirits.herokuapp.com/health"
        rollbackonhealthcheckfailed: true
