name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: oh-great-spirits
        heroku_email: ankeesler1@gmail.com
        healthcheck: "https://oh-great-spirits.herokuapp.com"
        rollbackonhealthcheckfailed: true
        usedocker: true
