name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Mod
      run: go mod download
    - name: Fmt
      run: test -z "$(go fmt ./...)"
    - name: Vet
      run: go vet -v ./...
    - name: Test
      run: go test -race -v ./...

  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm install
    - run: npm run check

  deploy:
    needs: [test-web, test-api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: oh-great-spirits
        heroku_email: ankeesler1@gmail.com
        healthcheck: "https://oh-great-spirits.herokuapp.com"
        rollbackonhealthcheckfailed: true
        usedocker: true
