name: CI

on:
  push:
    branches: [ main ]

jobs:
  codegen-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: image/codegen
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spirits-codegen:latest , ${{ secrets.DOCKERHUB_USERNAME }}/spirits-codegen:${{ env.GITHUB_SHA }}

  test-codegen:
    needs: [codegen-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        ./script/codegen.sh
        if [[ -n "$(git status --porcelain)" ]]; then
          git diff
          exit 1
        fi

  test-server:
    needs: [test-codegen]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Test
      run: go test -v ./...

  test-web:
    needs: [test-codegen]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - run: npm install
    - run: echo TODO

  build:
    needs: [test-web, test-server]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankeesler/spirits-server:latest

  test-integration:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: TODO
      run: echo TODO

  deploy:
    needs: [test-integration]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: TODO
      run: echo TODO
